config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :user_applications
  resources :user_applications do
    collection do
      post 'confirm'
    end
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  validates :name,
    presence: true

  validates :message,
    presence: { message: 'は必須です'}

  validates :email,
    presence: true
end

app/models/user_application.rb
class UserApplication < ActiveRecord::Base
  belongs_to :staff

  validates :name,
    presence: true

  validates :pref,
    presence: true

  validates :city,
    presence: true

  validates :town,
    presence: true

  validates :tel,
    presence: true

  validates :email,
    presence: true

  validates :participant_num,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }

  validates :staff_id,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :message, :email)
    end
end

app/controllers/user_applications_controller.rb
class UserApplicationsController < ApplicationController
  before_action :set_user_application, only: [:show, :edit, :update, :destroy]

  # GET /user_applications
  # GET /user_applications.json
  def index
    @user_applications = UserApplication.all
  end

  # GET /user_applications/1
  # GET /user_applications/1.json
  def show
  end

  # GET /user_applications/new
  def new
    @user_application = UserApplication.new
  end

  # POST /user_application/confirm
  def confirm
    @user_application = UserApplication.new(user_application_params)
    render :new if @user_application.invalid?
  end

  # GET /user_applications/1/edit
  def edit
  end

  # POST /user_applications
  # POST /user_applications.json
  def create
    @user_application = UserApplication.new(user_application_params)

    if params[:back]
      render :new
    elsif @user_application.save
      redirect_to @user_application, notice: 'User application was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /user_applications/1
  # PATCH/PUT /user_applications/1.json
  def update
    respond_to do |format|
      if @user_application.update(user_application_params)
        format.html { redirect_to @user_application, notice: 'User application was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_application }
      else
        format.html { render :edit }
        format.json { render json: @user_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_applications/1
  # DELETE /user_applications/1.json
  def destroy
    @user_application.destroy
    respond_to do |format|
      format.html { redirect_to user_applications_url, notice: 'User application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_application
      puts("params[:id]は", params[:id])
      @user_application = UserApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_application_params
      params.require(:user_application).permit(:name, :pref, :city, :town, :tel, :email, :participant_num, :staff_id)
    end
end

app/controllers/view_controller.rb
class ViewController < ApplicationController

  def form_for
    @staff = Staff.new
    # @book = Book.find(1)
  end

  def staff_select
    @staff = Staff.new(name: 'てすと')
    @staffs = Staff.select(:id, :name).distinct
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/user_applications_helper.rb
module UserApplicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fameal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.message %></td>
        <td><%= staff.email %></td>
        <td><%= link_to 'Show', staff %></td>
        <!-- <td><%= link_to 'Edit', edit_staff_path(staff) %></td> -->
        <!-- <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @staff.message %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>
<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>

app/views/user_applications/_form.html.erb
<%= form_for @user_application, url: {action: 'confirm'} do |f| %>
  <% if @user_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_application.errors.count, "error") %> prohibited this user_application from being saved:</h2>

      <ul>
      <% @user_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pref %><br>
    <%= f.text_field :pref %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.telephone_field :tel %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :participant_num %><br>
    <%= f.number_field :participant_num, min: 1, max: 100 %>
  </div>
  <% @staffs = Staff.select(:id, :name).distinct %>
  <div class="field">
    <%= f.label :staff_id %><br>
    <%= f.collection_select :staff_id, @staffs, :id, :name, :prompt => "選択してください" %>
<%
=begin
%>
    <select name="user_application[staff_id]">
      <% @staffs.each do |staff| %>
      <option value = <%= staff.id %>>
        <%= staff.name %>
      </option>
    <% end %>
    </select>
<%
=end
%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_applications/confirm.html.erb
<%= form_for @user_application do |f| %>
  <div class="field">
    name: <%= @user_application.name %><br>
    <%= f.hidden_field :name %>
  </div>
  <div class="field">
    pref: <%= @user_application.pref %><br>
    <%= f.hidden_field :pref %>
  </div>
  <div class="field">
    city: <%= @user_application.city %><br>
    <%= f.hidden_field :city %>
  </div>
  <div class="field">
    town: <%= @user_application.town %><br>
    <%= f.hidden_field :town %>
  </div>
  <div class="field">
    tel: <%= @user_application.tel %><br>
    <%= f.hidden_field :tel %>
  </div>
  <div class="field">
    email: <%= @user_application.email %><br>
    <%= f.hidden_field :email %>
  </div>
  <div class="field">
    participant_num: <%= @user_application.participant_num %><br>
    <%= f.hidden_field :participant_num, min: 1, max: 100 %>
  </div>
  <div class="field">
    staff_name: <%= @user_application.staff.name %><br>
    <%= f.hidden_field :staff_id %>
  </div>
    <div class="actions">
    <%= f.submit 'Back!', name: 'back' %>
  </div>
  <div class="actions">
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/user_applications/edit.html.erb
<h1>Editing User Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_application %> |
<%= link_to 'Back', user_applications_path %>

app/views/user_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Applications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pref</th>
      <th>City</th>
      <th>Town</th>
      <th>Tel</th>
      <th>Email</th>
      <th>Participant num</th>
      <th>Staff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_applications.each do |user_application| %>
      <tr>
        <td><%= user_application.name %></td>
        <td><%= user_application.pref %></td>
        <td><%= user_application.city %></td>
        <td><%= user_application.town %></td>
        <td><%= user_application.tel %></td>
        <td><%= user_application.email %></td>
        <td><%= user_application.participant_num %></td>
        <td><%= user_application.staff.name %></td>
        <td><%= link_to 'Show', user_application %></td>
        <!-- <td><%= link_to 'Edit', edit_user_application_path(user_application) %></td> -->
        <!-- <td><%= link_to 'Destroy', user_application, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User application', new_user_application_path %>

<%= debug(@user_applications) %>
<%= debug(@staffs) %>

app/views/user_applications/new.html.erb
<h1>New User Application</h1>

<%= render 'form' %>

<%= link_to 'Back', user_applications_path %>

app/views/user_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_application.name %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @user_application.pref %>
</p>

<p>
  <strong>City:</strong>
  <%= @user_application.city %>
</p>

<p>
  <strong>Town:</strong>
  <%= @user_application.town %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user_application.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_application.email %>
</p>

<p>
  <strong>Participant num:</strong>
  <%= @user_application.participant_num %>
</p>

<p>
  <strong>Staff:</strong>
  <%= @user_application.staff.name %>
</p>

<!-- <%= link_to 'Edit', edit_user_application_path(@user_application) %> | -->
<%= link_to 'Back', user_applications_path %>

app/views/view/staff_select.html.erb
<%= form_for(@staff) do |f| %>
  <%= f.collection_select :name, @staffs, :id, :name %>
<% end %>